[build]
  base = "www/admin"
  command = "chmod +x ../../admin-build.sh && ../../admin-build.sh"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  HOMESERVER_URL = "https://cravexv3-production.up.railway.app"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"







