# Railway Monorepo Configuration

[build]
builder = "DOCKERFILE"

# Synapse Backend Service
[[services]]
name = "disciplined-emotion"
dockerfile = "Dockerfile.synapse-prod"

# Element Web Frontend Service  
[[services]]
name = "bubbly-wonder"
dockerfile = "www/element-web/Dockerfile"

# Admin Panel Service
[[services]]
name = "cravexv2"
dockerfile = "www/admin/Dockerfile"