# Railway Monorepo Configuration

# Synapse Backend Service
[[services]]
name = "disciplined-emotion"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.synapse-prod"
watchPatterns = ["**"]

# Element Web Frontend Service  
[[services]]
name = "bubbly-wonder"

[services.build]
builder = "dockerfile"
dockerfilePath = "www/element-web/Dockerfile"
watchPatterns = ["www/element-web/**"]

# Admin Panel Service
[[services]]
name = "cravexv2"

[services.build]
builder = "dockerfile"
dockerfilePath = "www/admin/Dockerfile"
watchPatterns = ["www/admin/**"]