# Railway Monorepo Configuration

# Synapse Backend Service
[[services]]
name = "disciplined-emotion"
source = "."

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.synapse-prod"

# Element Web Frontend Service  
[[services]]
name = "bubbly-wonder"
source = "www/element-web"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Admin Panel Service
[[services]]
name = "cravexv2"
source = "www/admin"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"