# Railway Monorepo Configuration

# Synapse Backend Service
[[services]]
name = "disciplined-emotion"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.synapse-prod"

# Element Web Frontend Service  
[[services]]
name = "bubbly-wonder"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "www/element-web/Dockerfile"

# Admin Panel Service
[[services]]
name = "cravexv2"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "www/admin/Dockerfile"