# Railway Monorepo Configuration

[build]
builder = "DOCKERFILE"

# Synapse Backend Service
[[services]]
name = "perfect-creation"
dockerfile = "Dockerfile.synapse-prod"
root = "."

[services.variables]
SYNAPSE_SERVER_NAME = "${{ RAILWAY_PUBLIC_DOMAIN }}"
SYNAPSE_REPORT_STATS = "no"

# Element Web Frontend Service  
[[services]]
name = "tender-success"
dockerfile = "www/element-web/Dockerfile"
root = "www/element-web"

# Admin Panel Service
[[services]]
name = "cravexv2"
dockerfile = "www/admin/Dockerfile"
root = "www/admin"