# Railway Configuration - Synapse Only
# Element Web and Admin Panel are deployed on Netlify

[[services]]
name = "synapse"

[services.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
