# Railway Monorepo Configuration

[build]
builder = "DOCKERFILE"

# Synapse Backend Service
[[services]]
name = "disciplined-emotion"
dockerfile = "Dockerfile.synapse-prod"
dockerfilePath = "Dockerfile.synapse-prod"
root = "."

# Element Web Frontend Service  
[[services]]
name = "bubbly-wonder"
dockerfile = "Dockerfile"
dockerfilePath = "Dockerfile"
root = "www/element-web"

# Admin Panel Service
[[services]]
name = "cravexv2"
dockerfile = "Dockerfile"
dockerfilePath = "Dockerfile"
root = "www/admin"